#---------------------------------#
#            Rock RMS             #
#---------------------------------#

# version format
version: 0.1.{build}

# increment flag
pull_requests:
  do_not_increment_build_number: true

# Do not build on tags (GitHub only)
skip_tags: true

# operating system (build VM template)
image: Visual Studio 2017
configuration: Release
platform: Any CPU

# clone directory and depth
shallow_clone: true
clone_folder: C:\projects\Rock

# cache some things to speed up builds
cache:
- packages -> **\packages.config # cache the packages folder unless a project changes package dependancies
- C:\Users\appveyor\AppData\Local\NuGet\Cache # always cache the nuget cache


# scripts to run before build
before_build:
- ps: >-
    if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }
    
    (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe', "$nugetDir\NuGet.exe")
    
    nuget restore Rock.sln
    
    $src = "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\Facades"
    
    $dst = "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2"
    
    Get-ChildItem $src | Copy-Item -Destination $dst -Force
 
# build configuration
build:
  project: Rock.sln
  publish_wap: false
  parallel: true
  verbosity: minimal

artifacts:
- path: RockWeb
  name: RockWeb

# flag to stop building if an error throws
matrix:
  fast_finish: true

# test
test:
  assemblies:
  - Rock.Tests\**\*.dll